# Generated by Django 5.2.4 on 2025-07-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.employee')),
            ],
        ),
    ]
