# Generated by Django 5.2.4 on 2025-07-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
